version: '3.8'

services:
  test-database:
    container_name: test-database
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mase_hot
      MYSQL_USER: blog
      MYSQL_PASSWORD: redw94KfeWv
    ports:
      - '4308:3306'
    volumes:
      - database-mysql:/var/lib/mysql
  test-php:
    container_name: test-php
    build:
      context: .
      dockerfile: ./docker/php/local/Dockerfile
    ports:
      - '9002:9000'
    volumes:
      - .:/mase/
  test-nginx:
    container_name: test-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/local/Dockerfile
    ports:
      - '8082:80'
    volumes:
      - .:/mase/
    depends_on:
      - test-php

volumes:
  database-mysql:
